name: Auto Deploy

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Copy files to sms
      run: |
        cp -r /path/to/htdocs/Nehal/emp1/* /path/to/htdocs/Nehal/emp2/ /path/to/htdocs/Nehal/emp3/ /path/to/htdocs/Nehal/Emporium_franchise/

